/**
 * 预设搜索的别名（中文名、公司名、旧名）：按预设的 `name` 查。只用于添加供应商时的搜索，
 * 不参与显示。新增预设时，名字里搜不到的常用叫法加在这里。
 */
export const PRESET_SEARCH_ALIASES: Record<string, string> = {
  "AWS Bedrock (AKSK)": "amazon 亚马逊",
  "AWS Bedrock (API Key)": "amazon 亚马逊",
  "Baidu Qianfan Coding Plan": "百度 千帆 文心",
  "Baidu Qianfan Token Plan": "百度 千帆 文心",
  BaiLing: "蚂蚁 百灵 ling",
  Codex: "chatgpt openai gpt",
  DeepSeek: "深度求索",
  "Gemini Native": "google 谷歌",
  "GitHub Copilot": "copilot",
  "KAT-Coder": "快手 streamlake",
  Kimi: "月之暗面 moonshot",
  "Kimi For Coding": "月之暗面 moonshot",
  "Kimi For Coding Global": "月之暗面 moonshot",
  "Kimi Global": "月之暗面 moonshot",
  Longcat: "美团",
  MiniMax: "海螺",
  "MiniMax en": "海螺",
  ModelScope: "魔搭",
  QwenCloud: "通义 阿里 qwen",
  "QwenCloud For Coding": "通义 阿里 qwen",
  "QwenCloud Token Plan": "通义 阿里 qwen",
  SiliconFlow: "硅基流动",
  "SiliconFlow en": "硅基流动",
  StepFun: "阶跃星辰",
  "StepFun en": "阶跃星辰",
  "Tencent Token Plan": "腾讯 混元 hunyuan",
  "Tencent Token Plan (Intl)": "腾讯 混元 hunyuan",
  "Tencent Token Plan Enterprise Lite": "腾讯 混元 hunyuan",
  "Tencent Token Plan Enterprise Lite (Intl)": "腾讯 混元 hunyuan",
  "Tencent Token Plan Enterprise Pro": "腾讯 混元 hunyuan",
  "Tencent Token Plan Enterprise Pro (Intl)": "腾讯 混元 hunyuan",
  "Tu-zi": "兔子 兔子api tuzi",
  "xAI (Grok)": "grok",
  "Xiaomi MiMo": "小米",
  "Xiaomi MiMo Token Plan (China)": "小米",
  "Zhipu GLM": "智谱 glm bigmodel z.ai chatglm",
  "Zhipu GLM en": "智谱 glm bigmodel z.ai chatglm",
  优云智算: "ucloud",
  "优云智算Coding Plan": "ucloud",
  千问AI平台: "千问 通义 阿里 百炼 bailian aliyun qwen",
  "千问AI平台 Coding Plan": "千问 通义 阿里 百炼 bailian aliyun qwen",
  "千问AI平台 Token Plan": "千问 通义 阿里 百炼 bailian aliyun qwen",
  "火山 Agent Plan": "火山 豆包 doubao volcengine 方舟 ark 字节",
  "火山 Coding Plan": "火山 豆包 doubao volcengine 方舟 ark 字节",
  "火山 豆包AI": "火山 豆包 doubao volcengine 方舟 ark 字节",
};
